name: Enviroments Workflow

on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: true
        description: Environment name

jobs:
  print-environment-value:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Print Environment Values
        run: echo "${USERNAME} - ${PASSWORD}"