name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
        greeting:
            type: string
            default: Hello
            required: true
            description: Greeting to use in the message
jobs:
    manual-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Print greeting
              run: echo "${{ inputs.greeting }}, world!"
    